name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release-new-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
      - name: Build the package
        run: dotnet build
      - name: Publish the package
        run: dotnet publish
      - uses: papeloto/action-zip@v1
        with:
          files: Java-QuickCompiler/bin/Debug/netcoreapp3.1/publish/
          recursive: false
          dest: J.zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          path: ${{ github.workspace }}/J.zip
          asset_name: J.zip
          asset_content_type: application/zip
